### ISSUE TITLE
portfolio review

### ISSUE THREAD

**Issue by TamaraK** [livbarton21/portfolio#10]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Pages & images** | Barely started | Missing lots of pages & images | Has most of the pages, some placeholder images | All pages exist and are well done with complete imagery |
3-all pages fully complete and full of content
| **Personality & design** | Bland, boring, just another graphic designer | Fairly generic, visual design could be pushed more | Quality layouts and unique, personable content & design | Unique and recognizable as you, with engaging, personable content & design |
3- the design is kept light and beautiful and very fluid
| **Image quality** | Only placeholder images | Some portfolio piece images | Lots of images but low quality | High quality portfolio images — and lots of them |
3- wuper high quality images ,make this website shine
| **Accessibility** | No considerations | Added some alt attributes, nothing else | Just the basics: alt attributes, roles | Accessibility is well considered and tested |
3- seen on multiple browsers
| **Text content** | Fake content only | Some real content, some fake | All real content but with lots of errors | Real content, well written, no grammar or spelling errors |
3- all content is well written and needed no spelling errors as far as I can see 
| **Responsiveness** | Not responsive | Works on some screens | Responsive but with lots of awkwardness | Looks great on all screen sizes |
2-responsive in most ways but the banner seems a bit awkward on small screens
| **Code quality** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | Well indented, fully valid, good semantics |
3-code seems well laid out and logical

**Comment by livbarton21** [comment]
20/21
Thanks Tamara!
