### ISSUE TITLE
Peer Wireframe Critique

### ISSUE THREAD

**Issue by planetorium** [livbarton21/portfolio#3]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Pages & sections** |  |  | 2 |  |
| **Personality** |  |  |  | 3 |
| **Text content** |  |  |  | 3 |
| **Responsiveness** |  |  |  | 3 |
| **Code quality** |  | I |  | 3 |
Total: 14

**Comment by livbarton21** [comment]
Thanks Tori!
