### ISSUE TITLE
Peer Wireframe Critique

### ISSUE THREAD

**Issue by krystyna-Macleod** [livbarton21/portfolio#4]
Loving what you have done so far with the paper wireframe. I can really see where you are going with it. 

Just need the nav links to work and I believe a bit a breathing room between them about you and the gallery of your work. It feels to tight.

Overall looking good!

Creativeness: 4
Effectiveness: 4
Quality: 3
Effort: 4
Code Quality: 3

**Comment by livbarton21** [comment]
Thanks Krystyna!
